version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  # PostgreSQL Service
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: contactsdb
      POSTGRES_USER: contacts_user
      POSTGRES_PASSWORD: contacts_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: contact_service
    restart: always
    depends_on:
      - db
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/contactsdb
      SPRING_DATASOURCE_USERNAME: contacts_user
      SPRING_DATASOURCE_PASSWORD: contacts_pass
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  db_data:
  es_data:
